function J = halftone3x3(I)
dim = size(I);
J = zeros(dim.*3);
for i = 1:dim(1,1)
    for j = 1:dim(1,2)
        newI = (i-1)*3+1;
        newJ = (j-1)*3+1;
        if(I(i,j) < 26)
            J(newI,newJ) = 0;
            J(newI,newJ+1) = 0;
            J(newI,newJ+2) = 0;
            J(newI+1,newJ) = 0;
            J(newI+1,newJ+1) = 0;
            J(newI+1,newJ+2) = 0;
            J(newI+2,newJ) = 0;
            J(newI+2,newJ+1) = 0;
            J(newI+2,newJ+2) = 0;
        elseif(I(i,j) < 51)
            J(newI,newJ) = 255;
            J(newI,newJ+1) = 0;
            J(newI,newJ+2) = 0;
            J(newI+1,newJ) = 0;
            J(newI+1,newJ+1) = 0;
            J(newI+1,newJ+2) = 0;
            J(newI+2,newJ) = 0;
            J(newI+2,newJ+1) = 0;
            J(newI+2,newJ+2) = 0;
        elseif(I(i,j) < 77)
            J(newI,newJ) = 255;
            J(newI,newJ+1) = 0;
            J(newI,newJ+2) = 0;
            J(newI+1,newJ) = 0;
            J(newI+1,newJ+1) = 255;
            J(newI+1,newJ+2) = 0;
            J(newI+2,newJ) = 0;
            J(newI+2,newJ+1) = 0;
            J(newI+2,newJ+2) = 0;
        elseif(I(i,j) < 102)
            J(newI,newJ) = 255;
            J(newI,newJ+1) = 0;
            J(newI,newJ+2) = 0;
            J(newI+1,newJ) = 0;
            J(newI+1,newJ+1) = 255;
            J(newI+1,newJ+2) = 0;
            J(newI+2,newJ) = 0;
            J(newI+2,newJ+1) = 0;
            J(newI+2,newJ+2) = 255;   
        elseif(I(i,j) < 128)
            J(newI,newJ) = 255;
            J(newI,newJ+1) = 0;
            J(newI,newJ+2) = 0;
            J(newI+1,newJ) = 255;
            J(newI+1,newJ+1) = 0;
            J(newI+1,newJ+2) = 255;
            J(newI+2,newJ) = 0;
            J(newI+2,newJ+1) = 0;
            J(newI+2,newJ+2) = 255;
        elseif(I(i,j) < 153)
            J(newI,newJ) = 255;
            J(newI,newJ+1) = 0;
            J(newI,newJ+2) = 255;
            J(newI+1,newJ) = 0;
            J(newI+1,newJ+1) = 255;
            J(newI+1,newJ+2) = 0;
            J(newI+2,newJ) = 255;
            J(newI+2,newJ+1) = 0;
            J(newI+2,newJ+2) = 255;
        elseif(I(i,j) < 179)
            J(newI,newJ) = 255;
            J(newI,newJ+1) = 0;
            J(newI,newJ+2) = 255;
            J(newI+1,newJ) = 255;
            J(newI+1,newJ+1) = 0;
            J(newI+1,newJ+2) = 255;
            J(newI+2,newJ) = 255;
            J(newI+2,newJ+1) = 0;
            J(newI+2,newJ+2) = 255;
        elseif(I(i,j) < 204)
            J(newI,newJ) = 255;
            J(newI,newJ+1) = 0;
            J(newI,newJ+2) = 255;
            J(newI+1,newJ) = 255;
            J(newI+1,newJ+1) = 255;
            J(newI+1,newJ+2) = 255;
            J(newI+2,newJ) = 255;
            J(newI+2,newJ+1) = 0;
            J(newI+2,newJ+2) = 255;
        elseif(I(i,j) < 230)
            J(newI,newJ) = 255;
            J(newI,newJ+1) = 255;
            J(newI,newJ+2) = 255;
            J(newI+1,newJ) = 255;
            J(newI+1,newJ+1) = 0;
            J(newI+1,newJ+2) = 255;
            J(newI+2,newJ) = 255;
            J(newI+2,newJ+1) = 255;
            J(newI+2,newJ+2) = 255;
        else
            J(newI,newJ) = 255;
            J(newI,newJ+1) = 255;
            J(newI,newJ+2) = 255;
            J(newI+1,newJ) = 255;
            J(newI+1,newJ+1) = 255;
            J(newI+1,newJ+2) = 255;
            J(newI+2,newJ) = 255;
            J(newI+2,newJ+1) = 255;
            J(newI+2,newJ+2) = 255;
        end
    end
end
end

